#!/usr/bin/env bash
# Exit on error
set -e
set -u
set -o pipefail

#-------------------------------------------
# Run the test harness. Invoke as "ci/test".
#-------------------------------------------

# shellcheck source=/dev/null
. ci/functions.sh

info "Build"
./build

# generate change log and commit
run ci/gen-changelog

